### PR TITLE
Split for OGBDatasets 

### PR DESCRIPTION
**Pull request by Dsantra92**
The pr adds support for simple graph link split (#107) as well as support for splits in Heterogeneous OGB Datasets.

Need Fixing before merge: #167

### CODE REVIEW

**Comment by Dsantra92** [comment]
Tests and some fixes are left.

**Comment by Dsantra92** [comment]
The split for heterogeneous datasets with edge-level tasks needs to be addressed. Now that I have had the chance to think about it, I really don't want to change HeteroGraph API.

**Comment by CarloLucibello** [comment]
Can we add a test with the dataset mentioned  in https://github.com/JuliaML/MLDatasets.jl/issues/107#issuecomment-1120384637?

> The split for heterogeneous datasets with edge-level tasks needs to be addressed. 

it can be done in a separate PR if it is too involved

**Comment by Dsantra92** [comment]
Merge #170 before this

**Comment by Dsantra92** [comment]
I think we are in a good position to merge this @CarloLucibello

**Pull request merged**
