### PR TITLE
Use Pickle in favor of PyCall

### PR DESCRIPTION
**Pull request by yuehhua**

### CODE REVIEW

**Comment by yuehhua** [comment]
Now, it is loosen to v1.3.

**Comment by johnnychen94** [comment]
Thank you all for doing this!

**Comment by cossio** [comment]
Can we tag a release with this? I am having some issues with PyCall which I think would be fixed by this.

**Comment by johnnychen94** [comment]
Done.

**Comment by cossio** [comment]
Thanks!

**Pull request merged**
