### PR TITLE
render black digits on a whiteboard

### PR DESCRIPTION
**Pull request by ShuhuaGao**
Correct the display such that "
the digits are black on a white background".

### CODE REVIEW

**Comment by CarloLucibello** [comment]
Sorry we can't accept this PR, it's a breaking change not worth doing

**Comment by Evizero** [comment]
interesting. I think to remember that this actually used to be implemented that way. If this changed for some reason, which seems to be the case, then the docs should probably reflect it. They still claim:

```
The values are also color
corrected according to the website's description, which means that
the digits are black on a white background.
```

**Comment by ShuhuaGao** [comment]
Yes, I have the same point as @Evizero. The current implementation does not match the doc: either the code or the doc should be updated.

**Comment by CarloLucibello** [comment]
Sorry, didn't notice that. Change the docs?

**Comment by ShuhuaGao** [comment]
An alternative way is to introduce a keyword argument: `black_digits=false`. It will not cause breaking changes.

**Comment by CarloLucibello** [comment]
yes, that would be fine. The docs should reflect the default behavior though

**Comment by ShuhuaGao** [comment]
@CarloLucibello Hi, any advice on this PR? The default behaviour remains unchanged to avoid breaking changes, but the user has the freedom to render black digits on a white background.

**Comment by CarloLucibello** [comment]
Looks fine, can you add a test? e.g. that the returned array is reversed compared to the original one?

**Comment by ShuhuaGao** [comment]
@CarloLucibello Done. No idea why "Unit test / test (1.0, windows-latest) (pull_request) " failed. It does not seem to be caused by my changes.

**Comment by CarloLucibello** [comment]
thanks @ShuhuaGao

**Pull request merged**
